In [2]:
import sys
sys.path.append("../ingestion/python/src")
sys.path.append("../ingestion/python/LangGraph_Agent")

from utils import *
from langgraph.graph import StateGraph, START, END
from IPython.display import Image, display

from silver_enrichment import *
from graph_silver_enrichment import *
from APIendpoint import PlacesAPI
from database import Database
import pandas as pd
import os
from dotenv import load_dotenv
load_dotenv(override=True)

llm = LLM()
places_api = PlacesAPI(os.getenv('MAPS_APP_KEY'))
db = Database()

c:\Users\rolan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\langchain_core\utils\pydantic.py:41: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1 import BaseModel as BaseModelV1

In [2]:
r = db.execute("select * from serving.job_offer where city = 'Santiago del Estero';")
r

[{'id_offer': 'QABH-V9PfBb1b0IWAAAAAA==',
  'api_source': 'jsearch',
  'job_title': 'Data Engineer Analyst',
  'offer_description': "Blend is a premier AI services provider, committed to co-creating meaningful impact for its clients through the power of data science, AI, technology, and people. With a mission to fuel bold visions, Blend tackles significant challenges by seamlessly aligning human expertise with artificial intelligence. The company is dedicated to unlocking value and fostering innovation for its clients by harnessing world-class people and data-driven strategy.\n\nWe believe that the power of people and AI can have a meaningful impact on your world, creating more fulfilling work and projects for our people and clients. For more information, visit www.blend360.com\n\nWe are seeking a Data Engineer Analyst to contribute to our next level of growth and expansion.\n\nJob Description\n\nWhat is this position about?\n\nWe are looking for a Data Engineer Analyst to contribute to the design and implementation of scalable, domain-oriented data solutions for a high-impact enterprise initiative. You will work within a specific data domain — such as Ingestion, Customer Data, Enrichment, or Marketing Signals — ensuring high-quality, reliable data pipelines that power analytics and business-critical workflows. You may work 100% remotely from anywhere in Mexico!\n\n• Contribute to the design and development of scalable data pipelines on AWS (Glue, S3, Athena, Step Functions).\n• Build and optimize batch and streaming ingestion pipelines, including CDC-based architectures.\n• Support the design and implementation of data models aligned with business and analytics needs.\n• Ensure data quality, reliability, and performance across pipelines and datasets.\n• Collaborate with cross-functional teams to align technical solutions with business requirements.\n• Apply best practices in data engineering, including modular design, reusability, and governance.\n• Leverage AI-assisted development tools to improve productivity and code quality.\n• Proactively identify risks, bottlenecks, and optimization opportunities across data workflows.\n\nQualifications\n\n• Bachelor's degree in Computer Science, Data Engineering, Software Engineering, or equivalent field.\n• Hands-on experience with the AWS ecosystem, including Glue, S3, Athena, and Step Functions (required).\n• Solid proficiency in Python and PySpark for data pipeline development (required).\n• Experience with Snowflake or similar cloud data warehouse platforms (plus).\n• Understanding of data pipeline architecture and design patterns.\n• Exposure to CDC (Change Data Capture) patterns and streaming ingestion.\n• Experience with data modeling for analytics and reporting use cases.\n• Familiarity with AI-assisted development tools (plus).\n• Strong problem-solving skills and ability to work effectively in collaborative, agile environments.\nWhat about languages?\n\nEnglish: Advanced (required for effective communication with global teams).\n\nHow much experience must I have?\n\n3+ years of experience in Data Engineering or related disciplines, with hands-on work building and maintaining data pipelines on cloud platforms such as AWS.\n\nAdditional Information\n\nOur Perks and Benefits\n\n📚 Learning Opportunities:\n\n• Certifications in AWS (we are AWS Partners), Databricks, and Snowflake.\n• Access to AI learning paths to stay up to date with the latest technologies.\n• Study plans, courses, and additional certifications tailored to your role.\n• Access to Udemy Business, offering thousands of courses to boost your technical and soft skills.\n• English lessons to support your professional communication.\n👨🏽💻 Travel opportunities to attend industry conferences and meet clients.\n👩🏫 Mentoring and Development:\n\n• Career development plans and mentorship programs to help shape your path.\n🎁 Celebrations & Support:\n• Special day rewards to celebrate birthdays, work anniversaries, and other personal milestones.\n• Company-provided equipment.\n⚖️ Flexible working options to help you strike the right balance.\nOther benefits may vary according to your location in LATAM. For detailed information regarding the benefits applicable to your specific location, please consult with one of our recruiters.\n\nSo what are the next steps? Our team is eager to learn about you! Send us your resume or LinkedIn profile below and we'll explore working together!",
  'contract_type': 'fulltime',
  'is_remote': False,
  'alternative_job_titles': ['Data Engineer Analyst',
   'Data Engineer',
   'BI Developer'],
  'offer_languages': ['en'],
  'seniority': 'mid',
  'skills_languages': [''],
  'skills_frameworks': ['Python', 'PySpark'],
  'skills_aptitudes': ['Data pipeline development',
   'Cloud platform experience (AWS)',
   'Data modeling for analytics and reporting use cases',
   'Change Data Capture (CDC) patterns',
   'Streaming ingestion',
   'AI-assisted development tools',
   'Modular design',
   'Reusability',
   'Governance'],
  'skills_soft': [''],
  'score_job': 8.0,
  'score_skills': 9.0,
  'score_language': 6.0,
  'score_seniority': 7.0,
  'score_work_mode': 10.0,
  'score_company': 5.0,
  'score_location': 4.0,
  'score_relevancy': 7.05,
  'explanation': "score_job : Le poste de Data Engineer Analyst correspond à mes compétences et à mon expérience. Je possède des connaissances en Python, PySpark et en cloud platform AWS. Cependant, je n'ai pas d'expérience directe dans le domaine de l'analyse de données. (score 8/10)",
  'company_name': 'Blend',
  'website': 'http://www.blend360.com/',
  'primary_type': 'point_of_interest',
  'address': 'Av. Belgrano Sur 2576, 4200 Santiago del Estero, Argentina',
  'city': 'Santiago del Estero',
  'country': 'AR',
  'lat': -27.8073937,
  'lon': -64.2490104,
  'phone': '+54 9 385 614-0398',
  'business_status': 'OPERATIONAL',
  'company_mails': None,
  'job_publisher': 'BeBee',
  'offer_url': 'https://bebee.com/cl/jobs/data-engineer-analyst-blend-gran-santiago--techmap_cl_4418167023',
  'source_platform': 'BeBee',
  'published_at': '2026-05-22 01:36:30.896551+00',
  'collected_at': '2026-06-10 01:36:30.896551+00'}]

In [5]:
from rapidfuzz import process, fuzz

# Tes données et ton input
choix_possibles = ["java"]
input_utilisateur = "python"

# extractOne renvoie un tuple : (valeur, score, index)
resultat = process.extractOne(input_utilisateur, choix_possibles, scorer=fuzz.WRatio)

valeur, score, index = resultat

print(f"Meilleure correspondance : {valeur}")
print(f"Score de similarité : {score:.2f}%")

if score >= 80:
    print("Confiance élevée : on accepte le match.")
else:
    print("Confiance faible : on demande une confirmation à l'utilisateur.")

Meilleure correspondance : java
Score de similarité : 0.00%
Confiance faible : on demande une confirmation à l'utilisateur.

In [11]:
import country_converter as coco

cc = coco.CountryConverter()
print(cc.convert(names=['AR', 'FR'], to='name_short'))
# Résultat : ['Argentina', 'France']

['Argentina', 'France']

In [3]:
db = Database()

query = """
SELECT
    id_offer as job_id,
    api_source,
    job_title,
    contract_type,
    is_remote,
    offer_languages,
    seniority,
    (
        SELECT jsonb_agg(DISTINCT val)
        FROM (
            SELECT jsonb_array_elements_text(
                COALESCE(array_to_json(skills_languages)::jsonb, '[]'::jsonb) || 
                COALESCE(array_to_json(skills_frameworks)::jsonb, '[]'::jsonb) || 
                COALESCE(array_to_json(skills_aptitudes)::jsonb, '[]'::jsonb) || 
                COALESCE(array_to_json(skills_soft)::jsonb, '[]'::jsonb) ||
                COALESCE(array_to_json(alternative_job_titles)::jsonb, '[]'::jsonb)
            ) AS val
        ) sub
    ) AS all_keywords,
    score_relevancy,
    explanation,
    company_name,
    website,
    primary_type,
    city,
    country,
    lat as latitude,   -- Aliased for Plotly map compatibility
    lon as longitude,  -- Aliased for Plotly map compatibility
    offer_url,
    published_at,
    collected_at
FROM serving.job_offer;
"""
db.execute('SELECT serving.refresh_job_offer_if_stale();')
r = db.execute(query)

In [4]:
df = pd.DataFrame(r)

In [26]:
from collections import defaultdict

def generer_index_inverse(df):
    index = defaultdict(set)
    
    for idx, row in df.iterrows():
        # 1. Nettoyage : Récupère la liste, normalise chaque mot, supprime les doublons
        keywords = row.get('all_keywords', [])
        if not isinstance(keywords, list): continue
            
        mots_uniques = {kw.lower().strip() for kw in keywords}
        
        # 2. Indexation : Ajoute l'index de l'offre à chaque mot-clé
        for kw in mots_uniques:
            index[kw].add(idx)
            
    # Convertit les sets en listes pour une manipulation facilitée
    return {k: list(v) for k, v in index.items()}

# Utilisation
index_inverse = generer_index_inverse(df)
list(index_inverse.keys())

['python',
 'dataflow',
 'cloud run',
 'google cloud platform (gcp)',
 'dataform',
 'comunicación efectiva',
 'pub/sub',
 'terraform',
 'diseñar y mantener pipelines de datos robustos y escalables',
 'entendimiento del negocio',
 'resolución de problemas',
 'sql',
 'pensamiento crítico',
 'colaborar en iniciativas apoyadas por herramientas de ia',
 'aprendizaje continuo',
 'git/gitlab',
 'bigquery',
 'colaboración con equipos multidisciplinarios',
 'ci/cd',
 'cloud storage',
 'implementar buenas prácticas de calidad, monitoreo y gobierno de datos',
 'participar en procesos de migración y modernización',
 'data engineer semi senior',
 'etl',
 'explotación de datos',
 'ingeniero de datos para tiempo indefinido - cliente del area salud',
 'carga de datos',
 'ingeniero informático',
 'análisis de datos',
 'transformación de datos',
 'modelado de datos',
 'extracción de datos',
 'data engineer',
 'azure',
 'senior data engineer',
 't‑shaped senior data engineer',
 'cloud technologies',
 'microservicios',
 'desarrollo de flujos de datos en tiempo real',
 'spring boot',
 'unix/linux (shell)',
 'procesamiento distribuido',
 'scala',
 'data engineer – spark',
 'diseño de pipelines etl/elt',
 'analista big data',
 'java',
 'spark',
 'git',
 'automatización de procesos',
 'optimización de consultas sql',
 'gestión de versionamiento y despliegues',
 'cloud engineer',
 'backend engineer',
 'aws',
 'cloud computing',
 'software engineering best practices',
 'python data engineer',
 'event-driven architectures',
 'data engineering',
 'serverless solutions',
 'python developer',
 'bi developer',
 'computer science fundamentals',
 'sales intelligence specialist',
 'data analytics',
 'business intelligence specialist',
 'data visualization',
 'power bi developer',
 'semi senior data engineer',
 'desarrollo de pipelines de datos',
 'infraestructuras de datos',
 'machine learning',
 'nosql',
 'apis',
 'azure openai',
 'aws sagemaker',
 'kafka',
 'aws cloudformation',
 'data modeling',
 'data warehousing',
 'strong verbal and written communication skills in english',
 'airflow',
 'docker',
 'data infrastructure',
 'kubernetes',
 'senior oracle fusion data analyst',
 'erp',
 'oracle fusion',
 'remote erp expert',
 'herramientas de visualización (power bi, tableau)',
 'visualización de datos',
 'inteligencia artificial',
 'analista cx',
 'gestión de bases de datos',
 'excel',
 'automatización con ia',
 'gerente de crecimiento estratégico y sostenibilidad',
 'liderazgo',
 'automatización de flujos de información',
 'data engineer (azure)',
 'especialista en optimización de consultas y procesos',
 'gestión de tablas intermedias y datasets analíticos',
 'buena práctica en ingeniería de software',
 'optimización de consultas y procesos',
 'limpieza y validación de datos',
 'mantenibilidad del código',
 'desarrollador de lógica de negocio en databricks',
 'desarrollo de lógica de negocio',
 'validación de datos',
 'dataops',
 'colaboración',
 'ingeniero/a de datos',
 'automatización de pruebas',
 'control de versiones',
 'ingeniería de datos',
 'pruebas de regresión',
 'migraciones de plataformas de datos',
 'data analyst',
 'manejo de google workspace',
 'javascript',
 'writing skills',
 'fluency in spanish and english',
 'strong command of spanish and english grammar, punctuation, and technical writing standards',
 'database engineer',
 'c++',
 'remote data analyst',
 'sql developer',
 'data_analysis',
 'database_management',
 'area comercial rancagua',
 'interpretación de datos',
 'excel avanzado',
 'power bi',
 'plataformas cloud: gcp, aws y/o azure',
 'data engineer sr',
 'pyspark',
 'databricks',
 'diseño de pipelines de datos',
 'remoto - data engineer sr',
 'buenas prácticas de desarrollo',
 'consumer & market intelligence data analyst',
 'insight-driven data analyst',
 'business analyst',
 'experiencia previa en el área',
 'habilidades analíticas',
 'market research analyst',
 'ingeniero de datos',
 'ingeniero civil',
 'analista de datos',
 'data factory',
 'ingeniero analista de datos',
 'data engineering processes',
 'etl data engineer',
 'azure data engineer',
 'python (pyspark)',
 'sql server',
 'desarrollo de dashboards y reportes',
 'análisis de métricas comerciales',
 'trabajo en equipo',
 'gestion de calidad de datos',
 'ingenieria de datos',
 'looker & pipelines',
 'formalización y disponibilización de información',
 'documentación de procesos',
 'habilidades avanzadas en sql',
 'gestión de proyectos',
 'healthcare knowledge',
 'analytical reporting',
 'software developer',
 'backend development',
 'tableau',
 'security and compliance',
 'data quality',
 'monitoring and troubleshooting',
 'performance tuning',
 'git (azure devops)',
 'collaboration',
 'implementación y mantenimiento de pipelines etl/elt',
 'gerente de supply chain corporativo',
 'optimización de procesos internos en transformación, carga y reportería de datos',
 'ingeniero bi supply chain',
 'identificación y resolución de problemas en calidad y trazabilidad de datos',
 'análisis avanzado de datos',
 'desarrollador de software',
 'administración y mantenimiento de bases de datos',
 'desarrollo de flujos automatizados en python',
 'gestión de mantenimiento',
 'civil electricista',
 'ingeniero eléctrico',
 'data engineer - junior',
 'calidad del código',
 'diseño',
 'arquitectura de datos',
 'gestión de datos',
 'implementación',
 'data engineer - senior',
 'seguridad de datos',
 'escalabilidad',
 'mantenimiento',
 'data engineer sr - remoto - 1775',
 'buenas prácticas de ingeniería de datos',
 'grandes volúmenes de datos',
 'inglés avanzado',
 'herramientas de reportería/visualización',
 'generación de insights',
 'aprendizaje',
 'entornos de datos y plataformas analíticas',
 'manejo de sql',
 'desarrollo profesional',
 'especialista en inteligencia comercial',
 'software engineering specialist',
 'algorithms',
 'data structures',
 'english advanced',
 'remote ai data engineer',
 'servicios cloud',
 'automatización y orquestación de flujos de datos',
 'arquitecto de datos - big data',
 'procesamiento de grandes volúmenes de información',
 'calidad, gobernanza y seguridad de datos',
 'tecnologías big data',
 'herramientas de integración de datos',
 'arquitecturas cloud',
 'integración de múltiples fuentes de datos',
 'procesamiento de grandes volúmenes de datos (big data)',
 'optimización de procesos',
 'modelado y arquitectura de datos',
 'implementación de soluciones en la nube (aws, azure, gcp)',
 'herramientas de procesamiento distribuido',
 'bases de datos relacionales y no relacionales',
 'rubro transporte',
 'sql avanzado',
 'procesos etl/elt',
 'reportería',
 'integración de datos',
 'procesamiento de lenguaje natural',
 'data scientist',
 'modelamiento estadístico',
 'gcp',
 'data scientist senior - cl',
 'senior data engineer - cl',
 '- capacidad analítica de alto rendimiento',
 '- imaginación',
 'data engineer senior',
 '- resolución de problemas',
 '- lenguajes de programación',
 '- flexibilidad',
 '- amor por la innovación',
 '- orientación a objetivos',
 'remoto',
 '- liderazgo',
 'senior fullstack engineer (santiago)',
 'data science',
 'ai',
 'procesamiento de datos',
 'desarrollo de aplicaciones',
 'data engineer (aws)',
 'desarrollador de aplicaciones',
 'diseño de soluciones analíticas',
 'almacenamiento de datos',
 'api integration',
 'data transformation',
 'data ingestion',
 'large data processing',
 'data lakehouse concepts',
 'cloud',
 'big data',
 'herramientas etl',
 'versionamiento (git)',
 'gestión de presupuesto',
 'lider de people analytics',
 'optimización de recursos',
 'desarrollo de dashboards',
 'análisis financiero',
 'analista de capital humano',
 'modelado predictivo',
 'junior financial analyst',
 'financial data analyst',
 'seguimiento de procesos',
 'control de bases de datos',
 'análisis',
 'operations analyst',
 'ejecución de tareas críticas',
 'coordinación',
 'gestión de eventos y flujos de datos en tiempo real',
 'metodologías de ci/cd para despliegues de datos',
 'flujos de integración (etl/elt)',
 'procesamiento distribuido de datos',
 'git / github',
 'diseño de arquitecturas de datos',
 'arquitectura de data mesh',
 'capacidad analítica',
 'habilidades de trabajo colaborativo y comunicación',
 'arquitecto/a de soluciones de datos',
 'ingeniería de datos orientada a negocio',
 'arquitectura cloud',
 'calidad de datos',
 'data engineer aws & datalake',
 'trazabilidad de datos',
 'liderar',
 'análisis de información',
 'dirigir',
 'planificación',
 'establecimiento de relaciones interpersonales',
 'supervisar',
 'sintesis de información',
 'business intelligence developer',
 'organizar',
 'analista de inteligencia artificial',
 'uso de apis de ia',
 'ingeniero junior en inteligencia artificial',
 'desarrollador de herramientas de ia',
 'analista de data-driven',
 'non-payments manager',
 'analytical skills',
 'coreops - operational intelligence',
 'operational manager',
 'bi tools',
 'dynamodb',
 'sr software engineer',
 'software engineer',
 'desarrollador(a) backend aws',
 'junior data',
 'habilidades avanzadas en inglés',
 'remote semi-senior data engineer',
 'desarrollo de datos en la nube',
 'attention to detail',
 'teamwork',
 'problem-solving',
 'senior data cloud engineer',
 'communication',
 'devops',
 'scalable pipelines',
 'solutions engineer',
 'data',
 'junior solutions engineer',
 'sr. data engineer',
 'customer service',
 'data governance',
 'redshift',
 'snaplogic',
 'web services',
 'pentaho kettle',
 'agile software development methodologies',
 'sql/ddl queries/tuning techniques',
 'jitterbit',
 'data quality principles',
 'data warehouse design',
 'soap',
 'version control software',
 'informatica powercenter',
 'problem-solving and troubleshooting skills',
 'xml',
 'business analytics',
 'sqlserver',
 'oral and written communication skills',
 'database technologies',
 'rds',
 'rest',
 'talend openstudio',
 'data integration platforms',
 'postgres',
 'it operations best practices',
 'lucid',
 'accountability',
 'microsoft office suite',
 'airtable',
 'engagement',
 'sharepoint / teams',
 'self-development',
 'stakeholder management',
 'resourcefulness',
 'adoption',
 'optimization',
 'ingeniero sap successfactors',
 'gestión de cambios',
 'ingeniero soluciones ti',
 'análisis de incidentes',
 'code quality principles',
 'scala developer',
 'analista customer experience',
 'optimización',
 'collibra data governance',
 'microsoft purview',
 'modelado estadístico',
 'senior data analyst',
 'inglés (fluido)',
 'data storytelling',
 'data analysis',
 'compliance',
 'business intelligence',
 'kql',
 'data analyst ii',
 'data integrity',
 'governance',
 'etl pipelines',
 'práctica profesional - área de banco en gerencia de tecnología de banco ripley',
 'herramientas de visualización (power bi, aws quicksight)',
 'análisis e inteligencia comercial',
 'ecosistemas big data aws',
 'práctica profesional - arquitectura de datos',
 'py-spark',
 'data engineer – data pipelines',
 'herramientas de datos aws',
 'aerospace data pipelines',
 'apache airflow',
 'data engineer: real-time pipelines',
 'orquestación de pipelines',
 'data engineer specialist (providencia)',
 'creación de queries con sql sobre gcp bigquery',
 'control de cambios (git)',
 'desarrollo de pipelines en apache beam con gcp dataflow runner',
 'scripting (jupyterlab)',
 'modular design',
 'streaming ingestion',
 'reusability',
 'data modeling for analytics and reporting use cases',
 'data pipeline development',
 'data engineer analyst',
 'ai-assisted development tools',
 'change data capture (cdc) patterns',
 'cloud platform experience (aws)',
 'dama-dmbok',
 'python daqs',
 'análisis de riesgos',
 'integraciones',
 'programación',
 'ingeniero/a informático con manejo de data governance',
 'forensic attention to detail',
 'ability to take extreme ownership over your work',
 'positive mindset and can-do attitude',
 'oracle fusion developer',
 'consistently working 40 hours per week',
 'oracle fusion cloud applications',
 'agile/scrum',
 'prácticas de automatización',
 'orquestación de flujos de datos',
 'data engineer (semi sr)',
 'infraestructura como código (iac)',
 'automatización y ci/cd',
 'data_transformation',
 'data_visualization',
 'software development',
 'lead data engineer',
 'aws developer',
 'java developer',
 'microsoft_office',
 'commercial data analyst',
 'google sheets',
 'ml and data engineer',
 'object-oriented programming',
 'database management',
 'api development',
 'security and privacy awareness',
 'service-oriented programming',
 'containerization',
 'data lakes',
 'manejo avanzado de python',
 'manejo avanzado de sql',
 'aws pipelines',
 'data operation engineer',
 'dominio avanzado de sql',
 'dominio avanzado de python',
 'monitoreo y observabilidad (cloud logging)',
 'apache beam',
 'data engineer gcp',
 'buenas prácticas devops / infraestructura como código (terraform opcional)',
 'json',
 'parquet',
 'gitlab ci/cd',
 'nosql (firestore, mongodb)',
 'formatos avro',
 'bases de datos',
 'optimización de modelos de bases de datos',
 'data quality checks',
 'api interactions',
 'documentation',
 'data cataloging techniques',
 'data extraction',
 'validation',
 'data loading',
 'english communication (b2+ level)',
 'data lake patterns',
 'etl processes',
 'lineage tracking',
 'visualization techniques',
 'data pipelines',
 'data security',
 'data pipelines engineer',
 'dbt',
 'calidad del datos',
 'arquitectura en la nube',
 'gobernanza del dato',
 'statistical',
 'analytical',
 'senior product data analyst',
 'reverse etl workflows',
 'probabilistic modeling',
 'english (advanced)',
 'ai/ml model requirements',
 'remote data engineer - semi senior',
 'senior cloud engineer',
 'cloud data pipelines engineer',
 'mejoramiento de procesos',
 'back end development',
 'software engineering',
 'full stack development',
 'time management',
 'cloud data warehouse platforms (snowflake)',
 'capacidad para gestionar presupuestos',
 'curiosidad',
 'data analyst cmi cpd',
 'habilidad para comunicar ideas complejas',
 'matemáticas',
 'data profiling techniques',
 'anomaly detection',
 'completeness checks',
 'distribution analysis',
 'great expectations',
 'advanced analytics & insights hybrid',
 'ingeniero(a) de datos',
 'cientista de datos',
 'dax',
 'gobernanza de datos',
 'conocimiento de python para data',
 'conocimiento de herramientas de base de datos',
 'conocimiento de sql',
 'manejo de bi',
 'scrum',
 'uso de api',
 'jira',
 'estadística',
 'ml developer',
 'dominio en ml',
 'data scientist junior',
 'conocimiento en databricks ml',
 'automation',
 'oop',
 'ci/cd tools',
 'fabric',
 'flask',
 'sqlalchemy',
 'react',
 'full-stack developer',
 'django',
 'testable code',
 'vagrant',
 'data engineer (oci / python / spark)',
 'project management',
 'cloud-based data management',
 'ssrs',
 'data exploration',
 'adaptability',
 'semantic modeling',
 'continuous learning',
 't-sql',
 'azure virtual desktop',
 'communication (written and verbal)',
 'autonomous work',
 'qlik sense',
 'asynchronous work',
 'zoho projects / ticketing',
 'technical documentation',
 'query development',
 'microsoft 365, power apps, power automate, and flows',
 'agentic ai',
 'senior agentic ai engineer',
 'experience innovation leader',
 'dominio de herramientas databricks y aws',
 'diseño de pipelines',
 'azure data factory',
 'c#',
 'oop concepts',
 'spanish',
 'oop programming language',
 'informatica',
 'english',
 'snowflake',
 'various data formats',
 'data engineer, azure',
 'agile methodologies',
 'strong programming skills',
 'fluenz in spanish',
 'regulatory and compliance technology engineer',
 'big data developer',
 'interpretación de información',
 'análisis de rentabilidad y márgenes de negocio',
 'manejo de power bi',
 'data analyst comercial',
 'business acumen',
 'finance data analyst',
 'analytical thinking',
 'director of finance',
 'aws services',
 'ms office',
 'reconciliation',
 'communication skills',
 'query generation',
 'medical terminology',
 'edit checks',
 'data management',
 'data review',
 'sas reports',
 'data listing',
 'reasoning',
 'organizational ability',
 'ingeniero/a de datos aws',
 'trabajo colaborativo',
 'gobernanza y calidad de datos',
 'monitoreo y observabilidad',
 'pipelines de datos',
 'confluence',
 'github',
 'desarrollo de sistemas avanzados de seguimiento de marca',
 'investigación',
 'data platform engineer',
 'ai-driven insights',
 'ml & data engineer - real-time apis & data lakes',
 'python programming',
 'data services developer',
 'data cleaning',
 'self-directed work ethic',
 'troubleshooting',
 'html/css',
 'data validation',
 'matemático/a',
 'físico/a',
 'desarrollo de modelos de aprendizaje automático',
 'ingeniero/a eléctrico/a',
 'ingeniero/a en software',
 'pipelines, airflow engineer',
 'cobranza',
 'vaciado de datos',
 'normativas de riesgo financiero',
 'operaciones',
 'estructuración de información financiera',
 'desarrollo de negocios',
 'excel intermedio o avanzado',
 'vacio de datos',
 'analista de riesgo',
 'contabilidad',
 'analista financiero',
 'análisis de riesgo financiero',
 'tributación',
 'herramientas de gestión de datos y visualización',
 'full-stack engineer',
 'data pipeline management',
 'api design',
 'senior backend & data engineer',
 'strategic data insights analyst',
 'técnicas de analítica avanzada',
 'gestión de datos (sql)',
 'ingeniero analítico',
 'r',
 'análisis estadístico',
 'financial modeling',
 'prioritization',
 'business performance manager',
 'team management',
 'budgeting',
 'forecasting',
 'practicante de análisis de datos',
 'data analytics practicante',
 'analista de datos práctico',
 'desarrollo de análisis ad-hoc',
 'comunicación de resultados',
 'analytics sales specialist',
 'pipeline management',
 'consultative selling',
 'deal navigation',
 'demonstration',
 'relationship building',
 'sales strategy',
 'crm',
 'enterprise analytics account executive',
 'migrations, pipelines & apis',
 'pensamiento analítico',
 'orientación a resultados',
 'etl / elt',
 'comunicación de datos en insights accionables',
 'modelado de datos (relacional y analítico)',
 'etl developer',
 'operations specialist',
 'cross function hypercare support engineer',
 'security technology',
 'analista de negocios',
 'herramientas de programación',
 'conocimientos en machine learning y data science',
 'analista de riesgos',
 'analista de inversiones',
 'analista de clientes',
 'automatización de reportes',
 'generación de insights estratégicos',
 'data analyst senior',
 'herramientas de visualización',
 'diseño de informes',
 'habilidad analítica',
 'gestión presupuestaria',
 'construcción de relaciones',
 'data analyst - consumer & market intelligence',
 'metric manager',
 'etiquetado',
 'seguimiento',
 'it consultant',
 'data architect',
 'google tag manager',
 'looker studio',
 'data and martech specialist',
 'gemini enterprise',
 'digital analytics',
 'products up',
 'martech specialist',
 'google merchant center',
 'google analytics 4',
 'data specialist',
 'data lake',
 'especialista en datos',
 'automatización de pipelines',
 'microsoft fabric especialista',
 'modelado y análisis avanzado',
 'procesamiento de datos estructurados',
 'monitoreo de pipelines',
 'ingestión de datos',
 'microsoft fabric',
 'azure data services',
 'arquitecto de datos',
 'data warehouse',
 'c',
 'senior data engineer, cloud-scale',
 'trabajo en entornos cloud gcp',
 'modelamiento de datos',
 'gestión empresarial',
 'ingeniero(a) de clientes',
 'interpretación de datos complejos',
 'lenguajes de programación (phyton o r)',
 'sql en la nube',
 'técnicas estadísticas',
 'generación de insights accionables',
 'ia developer',
 'desarrollo de procesos de datos',
 'calidad de información',
 'terraform (iac)',
 'ia',
 'looker',
 'manejo de excel',
 'herramientas de visualizacion de datos',
 'automatización',
 'analisis de datos',
 'manejo de bases de datos',
 'generacion de insights',

In [26]:
df

,api_source,job_title,contract_type,is_remote,offer_languages,seniority,all_keywords,score_relevancy,explanation,company_name,website,primary_type,city,country,latitude,longitude,offer_url,published_at,collected_at
job_id,,,,,,,,,,,,,,,,,,,
-5_5YGoAcVzSUZGgAAAAAA==,jsearch,Data Engineer (Semi Senior),unknown,False,[es],mid,"[Aprendizaje continuo, BigQuery, CI/CD, Cloud ...",7.18,The job offer is for a Data Engineer position ...,2Brains,https://www.2brains.lat/,NaN,Santiago Metropolitan,CL,-33.431443,-70.609455,https://www.getonbrd.com/jobs/data-science-ana...,2026-06-06 01:36:30.896551+00,2026-06-10 01:36:30.896551+00
_M_aaszmcldoREuEAAAAAA==,jsearch,Ingeniero de Datos para Tiempo Indefinido - Cl...,internship,False,[es],senior,"[Análisis de Datos, Carga de Datos, ETL, Explo...",6.84,Relevancy score breakdown:\n\nScore Job (8/10)...,Abenis,NaN,NaN,NaN,NaN,NaN,NaN,https://bebee.com/cl/jobs/ingeniero-de-datos-p...,2026-05-28 01:36:30.898559+00,2026-06-10 01:36:30.898559+00
_9N8_eOMlNDGe7CyAAAAAA==,jsearch,Senior Data Engineer — Databricks,fulltime,False,[en],senior,"[Azure, Data Engineer, Senior Data Engineer, T...",7.67,Le poste de Senior Data Engineer correspond à ...,Infinite Lambda,https://infinitelambda.com,NaN,NaN,NaN,NaN,NaN,https://cl.trabajo.org/oferta-5486-c5fbdf8ddd3...,2026-06-06 01:36:30.897556+00,2026-06-10 01:36:30.897556+00
U6loljOK_B2XqcgbAAAAAA==,jsearch,Data Engineer – Spark,internship,False,[es],senior,"[Analista Big Data, Automatización de procesos...",7.44,Relevancy score breakdown:\n\nScore Job (8/10)...,Direccion Regional Metropolitana,NaN,government_office,Santiago Metropolitan,CL,-33.451096,-70.664436,https://cl.trabajo.org/oferta-5486-ff8c61091e4...,2026-06-07 01:36:30.896551+00,2026-06-10 01:36:30.896551+00
Tfisb5wQKBI3EowPAAAAAA==,jsearch,Data Engineer – Cloud,fulltime,False,[es],mid,"[Cloud Engineer, Data Engineer, ETL, SQL]",7.80,score_job,SOTRASER SCL,http://www.sotraser.cl/,transportation_service,Santiago Metropolitan,CL,-33.382429,-70.754979,https://cl.trabajo.org/oferta-5486-3bd1d69a563...,2026-06-07 01:36:30.897556+00,2026-06-10 01:36:30.897556+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
uBj-keEXIWE0UVP3AAAAAA==,jsearch,Data Scientist Analyst Junior,fulltime,False,[es],junior,"[Análisis y atención al detalle, Data Scientis...",7.95,Relevancy score breakdown:\n\nScore Job (8/10)...,IT-TALENT Headhunter SENIOR TI,http://www.it-talenthh.com/,service,Santiago Metropolitan,CL,-33.408566,-70.548711,https://cl.trabajo.org/oferta-4039-b3bd30fb7c9...,2026-06-08 01:36:30.899559+00,2026-06-10 01:36:30.899559+00
uFYWJt8ia_fxHEYVAAAAAA==,jsearch,Data Engineer Semi Senior – Cloud Data & Migra...,fulltime,False,[],senior,"[Cloud Data & Migrations Engineer, Data Engine...",7.85,Ce poste est très intéressant car il correspon...,Confidencial,NaN,market,Santiago Metropolitan,CL,-33.453594,-70.762382,https://www.jobleads.com/cl/job/data-engineer-...,2026-06-04 01:36:30.896551+00,2026-06-10 01:36:30.896551+00
uLldMxu-653zVf3hAAAAAA==,jsearch,Junior Data Engineer,unknown,False,[],junior,"[Data Engineer, Junior Data Scientist, data an...",6.82,score_job,Practia,NaN,NaN,Montevideo,UY,-34.904568,-56.136938,https://www.practia.uy/trabajar-en-practia/jun...,2026-06-09 01:36:30.897556+00,2026-06-10 01:36:30.897556+00
zgNIQX0lUQAqZd-XAAAAAA==,jsearch,Ingeniero de Datos - Jornada Hibrida,internship,False,[es],senior,"[Data Engineer, Excel, Ingeniero de Datos, Mic...",6.84,Relevancy score breakdown:\n\nScore Job (8/10)...,Abenis,NaN,NaN,NaN,NaN,NaN,NaN,https://bebee.com/cl/jobs/ingeniero-de-datos-j...,2026-05-28 01:36:30.898559+00,2026-06-10 01:36:30.898559+00
zllaPcERBkKOS3L7AAAAAA==,jsearch,AWS Data Engineer: Data Pipelines,fulltime,False,[es],mid,"[AWS Data Engineer: Data Pipelines, SQL, diseñ...",6.45,Score détaillé pour chaque critère,Womentech Network,https://www.womentech.net,NaN,NaN,NaN,NaN,NaN,https://cl.trabajo.org/oferta-2254-a2a8566fa4c...,2026-06-04 01:36:30.897556+00,2026-06-10 01:36:30.897556+00

In [7]:
import pycountry
_LANG_CACHE ={}
def convert_language_list(liste_codes):
    if not isinstance(liste_codes, list):
        return []
    
    noms = []
    for code in liste_codes:
        c = str(code).strip().lower()
        if not c:  # ignore les valeurs vides
            continue
        if c in _LANG_CACHE:
            noms.append(_LANG_CACHE[c])
            continue
        lang = pycountry.languages.get(alpha_2=c) or pycountry.languages.get(alpha_3=c)
        nom = lang.name if lang else c
        _LANG_CACHE[c] = nom
        noms.append(nom)
    return noms
# Ou applique sur TOUTE la colonne, pour voir le résultat global
df["test_languages"] = df["offer_languages"].apply(convert_language_list)
print(df["test_languages"].head(10))
df["offer_languages"].head(5)

0    [Spanish]
1    [Spanish]
2    [English]
3    [Spanish]
4    [Spanish]
5           []
6    [English]
7    [English]
8    [Spanish]
9    [English]
Name: test_languages, dtype: object

0    [es]
1    [es]
2    [en]
3    [es]
4    [es]
Name: offer_languages, dtype: object

In [17]:
df = pd.DataFrame(r)
df.set_index('job_id', inplace=True)

df2 = generer_index_inverse(df)
df2

NameError: name 'generer_index_inverse' is not defined

In [16]:
import country_converter as coco
import numpy as np
import pycountry
import pandas as pd
cc = coco.CountryConverter()
df = pd.DataFrame(r)
_LANG_CACHE = {}

def convert_language_list(liste_codes):
    if not isinstance(liste_codes, list):
        return []
    
    noms = []
    for code in liste_codes:
        c = str(code).strip().lower()
        if c in _LANG_CACHE:
            noms.append(_LANG_CACHE[c])
            continue
            
        lang = pycountry.languages.get(alpha_2=c) or pycountry.languages.get(alpha_3=c)
        nom = lang.name if lang else c
        _LANG_CACHE[c] = nom
        noms.append(nom)
    return noms

# 2. Appliquer la conversion uniquement sur les valeurs existantes
df.loc[mask, 'country_full'] = cc.convert(
    df.loc[mask, 'country'].tolist(), 
    to='name_short'
)

df.loc[mask_language, 'offer_languages_full'] = df.loc[mask_language, 'offer_languages'].apply(convertir_liste)
# 3. Les lignes NaN resteront NaN ou tu peux remplir par défaut
df['country_full'] = df['country_full'].replace('not found', np.nan)

In [13]:
df

,job_id,api_source,job_title,contract_type,is_remote,offer_languages,seniority,all_keywords,score_relevancy,explanation,...,primary_type,city,country,latitude,longitude,offer_url,published_at,collected_at,country_full,offer_languages_full
0,-5_5YGoAcVzSUZGgAAAAAA==,jsearch,Data Engineer (Semi Senior),unknown,False,[es],mid,"[Aprendizaje continuo, BigQuery, CI/CD, Cloud ...",7.18,The job offer is for a Data Engineer position ...,...,NaN,Santiago Metropolitan,CL,-33.431443,-70.609455,https://www.getonbrd.com/jobs/data-science-ana...,2026-06-06 01:36:30.896551+00,2026-06-10 01:36:30.896551+00,Chile,[Spanish]
1,_M_aaszmcldoREuEAAAAAA==,jsearch,Ingeniero de Datos para Tiempo Indefinido - Cl...,internship,False,[es],senior,"[Análisis de Datos, Carga de Datos, ETL, Explo...",6.84,Relevancy score breakdown:\n\nScore Job (8/10)...,...,NaN,NaN,NaN,NaN,NaN,https://bebee.com/cl/jobs/ingeniero-de-datos-p...,2026-05-28 01:36:30.898559+00,2026-06-10 01:36:30.898559+00,nan,[Spanish]
2,_9N8_eOMlNDGe7CyAAAAAA==,jsearch,Senior Data Engineer — Databricks,fulltime,False,[en],senior,"[Azure, Data Engineer, Senior Data Engineer, T...",7.67,Le poste de Senior Data Engineer correspond à ...,...,NaN,NaN,NaN,NaN,NaN,https://cl.trabajo.org/oferta-5486-c5fbdf8ddd3...,2026-06-06 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,nan,[English]
3,U6loljOK_B2XqcgbAAAAAA==,jsearch,Data Engineer – Spark,internship,False,[es],senior,"[Analista Big Data, Automatización de procesos...",7.44,Relevancy score breakdown:\n\nScore Job (8/10)...,...,government_office,Santiago Metropolitan,CL,-33.451096,-70.664436,https://cl.trabajo.org/oferta-5486-ff8c61091e4...,2026-06-07 01:36:30.896551+00,2026-06-10 01:36:30.896551+00,Chile,[Spanish]
4,Tfisb5wQKBI3EowPAAAAAA==,jsearch,Data Engineer – Cloud,fulltime,False,[es],mid,"[Cloud Engineer, Data Engineer, ETL, SQL]",7.80,score_job,...,transportation_service,Santiago Metropolitan,CL,-33.382429,-70.754979,https://cl.trabajo.org/oferta-5486-3bd1d69a563...,2026-06-07 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,Chile,[Spanish]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,uBj-keEXIWE0UVP3AAAAAA==,jsearch,Data Scientist Analyst Junior,fulltime,False,[es],junior,"[Análisis y atención al detalle, Data Scientis...",7.95,Relevancy score breakdown:\n\nScore Job (8/10)...,...,service,Santiago Metropolitan,CL,-33.408566,-70.548711,https://cl.trabajo.org/oferta-4039-b3bd30fb7c9...,2026-06-08 01:36:30.899559+00,2026-06-10 01:36:30.899559+00,Chile,[Spanish]
761,uFYWJt8ia_fxHEYVAAAAAA==,jsearch,Data Engineer Semi Senior – Cloud Data & Migra...,fulltime,False,[],senior,"[Cloud Data & Migrations Engineer, Data Engine...",7.85,Ce poste est très intéressant car il correspon...,...,market,Santiago Metropolitan,CL,-33.453594,-70.762382,https://www.jobleads.com/cl/job/data-engineer-...,2026-06-04 01:36:30.896551+00,2026-06-10 01:36:30.896551+00,Chile,[]
762,uLldMxu-653zVf3hAAAAAA==,jsearch,Junior Data Engineer,unknown,False,[],junior,"[Data Engineer, Junior Data Scientist, data an...",6.82,score_job,...,NaN,Montevideo,UY,-34.904568,-56.136938,https://www.practia.uy/trabajar-en-practia/jun...,2026-06-09 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,Uruguay,[]
763,zgNIQX0lUQAqZd-XAAAAAA==,jsearch,Ingeniero de Datos - Jornada Hibrida,internship,False,[es],senior,"[Data Engineer, Excel, Ingeniero de Datos, Mic...",6.84,Relevancy score breakdown:\n\nScore Job (8/10)...,...,NaN,NaN,NaN,NaN,NaN,https://bebee.com/cl/jobs/ingeniero-de-datos-j...,2026-05-28 01:36:30.898559+00,2026-06-10 01:36:30.898559+00,nan,[Spanish]
764,zllaPcERBkKOS3L7AAAAAA==,jsearch,AWS Data Engineer: Data Pipelines,fulltime,False,[es],mid,"[AWS Data Engineer: Data Pipelines, SQL, diseñ...",6.45,Score détaillé pour chaque critère,...,NaN,NaN,NaN,NaN,NaN,https://cl.trabajo.org/oferta-2254-a2a8566fa4c...,2026-06-04 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,nan,[Spanish]

In [2]:
import pycountry

def code_vers_langue(code_iso):
    try:
        # Recherche par code ISO 639-1 (ex: 'en') ou 639-3 (ex: 'eng')
        langue = pycountry.languages.get(alpha_2=code_iso.lower())
        if not langue:
            langue = pycountry.languages.get(alpha_3=code_iso.lower())
            
        return langue.name if langue else code_iso
    except Exception:
        return code_iso

# Test de la fonction
print(code_vers_langue("en"))  # Sortie : English
print(code_vers_langue("es"))  # Sortie : Spanish
print(code_vers_langue("fr"))  # Sortie : French

English
Spanish
French

In [38]:
df

,job_id,api_source,job_title,contract_type,is_remote,offer_languages,seniority,all_keywords,score_relevancy,explanation,...,website,primary_type,city,country,latitude,longitude,offer_url,published_at,collected_at,country_full
0,-5_5YGoAcVzSUZGgAAAAAA==,jsearch,Data Engineer (Semi Senior),unknown,False,[es],mid,"[Aprendizaje continuo, BigQuery, CI/CD, Cloud ...",7.18,The job offer is for a Data Engineer position ...,...,https://www.2brains.lat/,NaN,Santiago Metropolitan,CL,-33.431443,-70.609455,https://www.getonbrd.com/jobs/data-science-ana...,2026-06-06 01:36:30.896551+00,2026-06-10 01:36:30.896551+00,Chile
1,_M_aaszmcldoREuEAAAAAA==,jsearch,Ingeniero de Datos para Tiempo Indefinido - Cl...,internship,False,[es],senior,"[Análisis de Datos, Carga de Datos, ETL, Explo...",6.84,Relevancy score breakdown:\n\nScore Job (8/10)...,...,NaN,NaN,NaN,NaN,NaN,NaN,https://bebee.com/cl/jobs/ingeniero-de-datos-p...,2026-05-28 01:36:30.898559+00,2026-06-10 01:36:30.898559+00,NaN
2,_9N8_eOMlNDGe7CyAAAAAA==,jsearch,Senior Data Engineer — Databricks,fulltime,False,[en],senior,"[Azure, Data Engineer, Senior Data Engineer, T...",7.67,Le poste de Senior Data Engineer correspond à ...,...,https://infinitelambda.com,NaN,NaN,NaN,NaN,NaN,https://cl.trabajo.org/oferta-5486-c5fbdf8ddd3...,2026-06-06 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,NaN
3,U6loljOK_B2XqcgbAAAAAA==,jsearch,Data Engineer – Spark,internship,False,[es],senior,"[Analista Big Data, Automatización de procesos...",7.44,Relevancy score breakdown:\n\nScore Job (8/10)...,...,NaN,government_office,Santiago Metropolitan,CL,-33.451096,-70.664436,https://cl.trabajo.org/oferta-5486-ff8c61091e4...,2026-06-07 01:36:30.896551+00,2026-06-10 01:36:30.896551+00,Chile
4,Tfisb5wQKBI3EowPAAAAAA==,jsearch,Data Engineer – Cloud,fulltime,False,[es],mid,"[Cloud Engineer, Data Engineer, ETL, SQL]",7.80,score_job,...,http://www.sotraser.cl/,transportation_service,Santiago Metropolitan,CL,-33.382429,-70.754979,https://cl.trabajo.org/oferta-5486-3bd1d69a563...,2026-06-07 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,Chile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,uBj-keEXIWE0UVP3AAAAAA==,jsearch,Data Scientist Analyst Junior,fulltime,False,[es],junior,"[Análisis y atención al detalle, Data Scientis...",7.95,Relevancy score breakdown:\n\nScore Job (8/10)...,...,http://www.it-talenthh.com/,service,Santiago Metropolitan,CL,-33.408566,-70.548711,https://cl.trabajo.org/oferta-4039-b3bd30fb7c9...,2026-06-08 01:36:30.899559+00,2026-06-10 01:36:30.899559+00,Chile
761,uFYWJt8ia_fxHEYVAAAAAA==,jsearch,Data Engineer Semi Senior – Cloud Data & Migra...,fulltime,False,[],senior,"[Cloud Data & Migrations Engineer, Data Engine...",7.85,Ce poste est très intéressant car il correspon...,...,NaN,market,Santiago Metropolitan,CL,-33.453594,-70.762382,https://www.jobleads.com/cl/job/data-engineer-...,2026-06-04 01:36:30.896551+00,2026-06-10 01:36:30.896551+00,Chile
762,uLldMxu-653zVf3hAAAAAA==,jsearch,Junior Data Engineer,unknown,False,[],junior,"[Data Engineer, Junior Data Scientist, data an...",6.82,score_job,...,NaN,NaN,Montevideo,UY,-34.904568,-56.136938,https://www.practia.uy/trabajar-en-practia/jun...,2026-06-09 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,Uruguay
763,zgNIQX0lUQAqZd-XAAAAAA==,jsearch,Ingeniero de Datos - Jornada Hibrida,internship,False,[es],senior,"[Data Engineer, Excel, Ingeniero de Datos, Mic...",6.84,Relevancy score breakdown:\n\nScore Job (8/10)...,...,NaN,NaN,NaN,NaN,NaN,NaN,https://bebee.com/cl/jobs/ingeniero-de-datos-j...,2026-05-28 01:36:30.898559+00,2026-06-10 01:36:30.898559+00,NaN
764,zllaPcERBkKOS3L7AAAAAA==,jsearch,AWS Data Engineer: Data Pipelines,fulltime,False,[es],mid,"[AWS Data Engineer: Data Pipelines, SQL, diseñ...",6.45,Score détaillé pour chaque critère,...,https://www.womentech.net,NaN,NaN,NaN,NaN,NaN,https://cl.trabajo.org/oferta-2254-a2a8566fa4c...,2026-06-04 01:36:30.897556+00,2026-06-10 01:36:30.897556+00,NaN